### ISSUE TITLE
AtomでESLintのプラグインlinter-eslintを利用したとき、Error: Cannot mark location in editor for (no-multiple-empty-lines)が出力される。

### ISSUE THREAD

**Issue by tairas** [k-kono/eslint-config-imart#2]
## 環境  
- OS : Windows10  
- Atom Version1.12.5  
- ESLint v2.9.0  
- linter-eslint 8.0.0  

## エラーメッセージ

```
Error: Cannot mark location in editor for (no-multiple-empty-lines) - (More than 2 blank lines not allowed.) at line (105) column (2)
Error: Cannot mark location in editor for (no-multiple-empty-lines) - (More than 2 blank lines not allowed.) at line (105) column (2)
    at C:\Users\hogehoge\.atom\packages\linter-eslint\lib\main.js:227:21
    at Array.map (native)
    at C:\Users\hogehoge\.atom\packages\linter-eslint\lib\main.js:192:27
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

## 解決案  
ESlint v3.5.0で修正されているようです。
https://github.com/AtomLinter/linter-eslint/issues/732

**Comment by kotodamagic** [comment]
62be09f228ba8eefa09e9c55252f3ae25b885912 にてeslintへの依存性を削除しました。

**Comment by ghost** [comment]
62be09f228ba8eefa09e9c55252f3ae25b885912 にてeslintへの依存性を削除しました。
